refresh_rate: 30 seconds

appenders:
  stdout:
    kind: console

  requests:
    kind: file
    path: "log/requests.log"
    encoder:
      pattern: "{d} - {m}{n}"
      
  default:
    kind: file
    path: "log/default.log"
    encoder:
      pattern: "{d} - {m}{n}"


root:
  level: info
  appenders:
    - default
    - stdout

loggers:
  app::backend::db:
    level: info

  app::requests:
    level: info
    appenders:
      - requests
    additive: false
    