refresh_rate: 30 seconds

appenders:
  stdout:
    kind: console
      
  default:
    kind: file
    path: "log/client.log"
    encoder:
      pattern: "{d} - {m}{n}"


root:
  level: info
  appenders:
    - default
    - stdout

loggers:
  app::backend::db:
    level: trace

  tdengine:
    level: trace
    appenders:
      - default
      - stdout
    additive: false

  websocket:
    level: info
    appenders:
      - default
    additive: false

    