refresh_rate: 30 seconds

appenders:
  stdout:
    kind: console
      
  default:
    kind: file
    path: "log/default.log"
    encoder:
      pattern: "{d} - {m}{n}"


root:
  level: trace
  appenders:
    - default
    - stdout

loggers:
  app::backend::db:
    level: trace

    